### ISSUE TITLE
O exemplo no asciicinema não está mais disponível

### ISSUE THREAD

**Issue by feliperuiz** [HotelUrbano/challenge-echo#11]
![Screenshot_2019-08-28 hurbcom challenge-lima](https://user-images.githubusercontent.com/3370823/63889721-f1890e00-c9b7-11e9-8176-07aef628c3b5.png)

Talvez o input e output esperado desse exemplo possam ser adicionados ao repositório?

**Comment by brunofurmon** [comment]
Deprecated. Closing
