### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by allanbatista** [HotelUrbano/challenge-echo#2]
Boa tarde.

Fiquei com uma dúvida sobre o funcionamento da rotação. A documentação não especifica em qual sentido ela deve acontecer, então implementei somente utilizando a rotação sentido horario. Mas a movimentação do "drone" ficou estranha.... :(

A rotação deve continua seguindo esse modelo?

Outra coisa (double check), que também fiquei na dúvida são os comandos "D" e "E", que além de "andar" para os lados ele também rotaciona. É isso mesmo?

**Comment by zanaca** [comment]
Em qualquer sentido.

"D" e "E" são giros.
