### ISSUE TITLE
Dúvida sobre o enunciado

### ISSUE THREAD

**Issue by vinnyamancio** [HotelUrbano/challenge-echo#6]
"Ex: "DFFEEFDFE" Nesse exemplo vão ser tiradas 5 fotos."
Partindo do princípio que não fotografamos área que já passamos, não achei a possibilidade de ter 5 fotografias nesse exemplo, e gostaria de saber se o enunciado está correto.

:(

**Comment by zanaca** [comment]
Está correto!

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.
