### ISSUE TITLE
Dúvidas para executar o código em docker

### ISSUE THREAD

**Issue by vinnyamancio** [HotelUrbano/challenge-echo#8]
Olá, tudo bem?

Estou com uma dúvida com relação ao docker, já dei fork e pull request no desafio, porém não sei como colocar o código para rodar em docker. Vocês saberiam me explicar?

Agradeço desde já.

Atenciosamente,
Vinícius Amâncio

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.
